//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Automobilista2Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Automobilista2Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To enable Automobilista 2 telemetry: 
        ///&lt;br&gt;
        ///Go into Options-&gt;System and set UDP frequency to 2, and protocol version to project CARS 2.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///    &quot;GameName&quot;: &quot;Automobilista2&quot;,
        ///    &quot;Name&quot;: &quot;Default&quot;,
        ///    &quot;Components&quot;: [
        ///        {
        ///            &quot;Constant&quot;: false,
        ///            &quot;Input_index&quot;: 3,
        ///            &quot;Output_index&quot;: 4,
        ///            &quot;MultiplierPos&quot;: 20.0,
        ///            &quot;MultiplierNeg&quot;: 0.0,
        ///            &quot;Offset&quot;: 0.5,
        ///            &quot;Inverse&quot;: false,
        ///            &quot;Limit&quot;: -1.0,
        ///            &quot;Smoothing&quot;: 0.75192505,
        ///            &quot;Enabled&quot;: true,
        ///            &quot;Spikeflatter&quot;: {
        ///                &quot;Enabled&quot;: false,
        ///                &quot;Limit&quot;: 100.0, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string profile {
            get {
                return ResourceManager.GetString("profile", resourceCulture);
            }
        }
    }
}
